package com.ohlavrac.inventory_manager.domain.enums;

public enum OrderStatus {
    PENDING, //WHAIT FOR UPDATE (ACCEPTED OR REFUSED)
    ACCEPTED, //ACCEPTED, RESERVE THE PRODUCT AMOUNT BUT CAN BE CANCELED
    REFUSED, //JUST REFUSED
    CANCELED, //JUST CANCELED
    COMPLETED //CANT BE CANCELED OR REFUSED (NEED ACCEPTED STATUS TO UPDATE TO COMPLETED)
}
